
cc_library(
  name = "meta",
  srcs = ['meta.cc'],
  hdrs = ['meta.h'],
  deps = [],
  visibility = ['//visibility:public'],
)

cc_binary(
  name = "metamain",
  srcs = ["metamain.cc"],
  deps = ["meta"],
  visibility = ['//visibility:public'],
)

