
py_test(
  name = "root_test",
  main = "__init__.py",
  srcs = ['__init__.py'],
  deps = [
    "//metax/root:root",
    "//metax/test:test",
  ],
  size = "small",
  visibility = ['//visibility:public'],
)
