# target default:
#   Disable the dangerous practice of having the first target be default target.
default:
	@echo "Specify an explicit target"

# target main:
main: main.cc
	g++ -std=c++17 -o main main.cc

.FORCE:
