cc_library(
  # This target is included in every C++ header file, so any files defined by
  # it or its dependencies are available.
  name = "__Meta__",
  hdrs = ["__Meta__.h"],
  srcs = ["__Meta__.cc"],
  deps = [],
  visibility = ["//visibility:public"],
)
