# ----------------------------------------------------------------------
# C++ External Dependencies

# See
#   https://docs.bazel.build/versions/master/cpp-use-cases.html#writing-and-running-c-tests
#   https://docs.bazel.build/versions/master/cpp-use-cases.html#including-external-libraries
#   https://docs.bazel.build/versions/master/external.html
#   https://github.com/smyte/smyte-db/blob/master/third_party/workspace.bzl
#   https://github.com/smyte/cpp-build/blob/master/WORKSPACE
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = 'gtest',
    build_file_content = """
cc_library(
    name = 'gtest',
    srcs = glob(['googletest/src/*.cc'], exclude = ['googletest/src/gtest-all.cc']),
    hdrs = glob(['**/*.h', 'googletest/src/*.cc']),
    includes = [
        './',
        'googletest',
        'googletest/include',
        'include'
    ],
    linkopts = ['-pthread'],
    visibility = ['//visibility:public'],
)
cc_library(
    name = 'gmock',
    srcs = glob(['googlemock/src/*.cc'], exclude = ['googlemock/src/gmock-all.cc']),
    hdrs = glob(['**/*.h', 'googlemock/src/*.cc']),
    includes = [
        './',
        'googlemock',
        'googlemock/include',
        'include'
    ],
    deps = [':gtest'],
    linkopts = ['-pthread'],
    visibility = ['//visibility:public'],
)
""",
    url = 'https://github.com/google/googletest/archive/release-1.8.1.zip',
    strip_prefix = 'googletest-release-1.8.1',
    sha256 = '927827c183d01734cc5cfef85e0ff3f5a92ffe6188e0d18e909c5efebf28a0c7'
)

# Abseil for C++
#  - https://abseil.io/docs/cpp/quickstart
#  - the WORKSPACE in 'git clone https://github.com/abseil/abseil-hello.git'
#    uses the following (docs only discuss local_repository, but http_archive
#    is better).
http_archive(
  name = "absl",
  urls = ["https://github.com/abseil/abseil-cpp/archive/7c7754fb3ed9ffb57d35fe8658f3ba4d73a31e72.zip"],  # 2019-03-14
  strip_prefix = "abseil-cpp-7c7754fb3ed9ffb57d35fe8658f3ba4d73a31e72",
  sha256 = "71d00d15fe6370220b6685552fb66e5814f4dd2e130f3836fc084c894943753f",
)
