# ----------------------------------------------------------------------
# C++ External Dependencies

# See the "Including external libraries" section of
#   http://www.bazel.io/docs/tutorial/cpp.html
new_http_archive(
  name = 'gtest',
  url = 'https://googletest.googlecode.com/files/gtest-1.7.0.zip',
  sha256 = '247ca18dd83f53deb1328be17e4b1be31514cedfc1e3424f672bf11fd7e0d60d',
  build_file = 'BUILD.gtest',
  strip_prefix = "gtest-1.7.0",
)
