default:
	@echo "Specify explicit target"

index:
	python absl-index.py
	@echo "Visit file://$(shell pwd)/absl.html"

# see https://abseil.io/docs/cpp/quickstart
abseil-cpp:
	git clone https://github.com/abseil/abseil-cpp.git

# quickstart demo: https://abseil.io/docs/cpp/quickstart
abseil-hello:
	git clone https://github.com/abseil/abseil-hello.git
