cc_library(
    name = "namespace",
    srcs = ["namespace.cc"],
    hdrs = ["namespace.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "Class",
    srcs = ["Class.cc"],
    hdrs = ["Class.h"],
    visibility = ["//visibility:public"],
)

