
py_test(
  name = "cards2_test",
  main = "__init__.py",
  srcs = ['__init__.py'],
  deps = [
    "//demo/cards2:cards2",
    "//meta:testing",
  ],
  size = "small",
  visibility = ['//visibility:public'],
)
