cc_binary(
    name = "hello",
    srcs = ["hello.cc"],
)

cc_binary(
    name = "main",
    srcs = ["main.cc"],
)

cc_binary(
    name = "any",
    srcs = ["any.cc"],
)

cc_binary(
    name = "any_clang",
    srcs = ["any-clang.cc"],
)
